version: '2.2'

services:
  stalker:
    build:
      context: .
      dockerfile: Dockerfile-stalker
      args:
        - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
        - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
        - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    image: stalker:latest
    container_name: stalker 
    volumes:
      - static:/usr/local/stalker/static
    depends_on:
      - es01
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - STALKER_HTTP_PORT=${STALKER_HTTP_PORT}
        - STALKER_HTTPS_PORT=${STALKER_HTTPS_PORT}
    image: nginx-stalker:latest
    container_name: stalker_web
    volumes:
        - static:/static
    ports:
      - "${STALKER_HTTP_PORT}:80"
      - "${STALKER_HTTPS_PORT}:443"
    restart: always

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: stalker_es01
    environment:
      - node.name=stalker_es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always

volumes:
  static:
    driver: local
  esdata01:
    driver: local

